# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: The Resonant Dark Universe # Your website's main title
first_name: Joshua
middle_name: Daniel
last_name: Knoechelman
contact_note: >
  You can reach me via email. My work is available on Zenodo and my ORCID profile is linked below.

description: > # A short description of your site for search engines
  The official website for the Resonant Dark Universe (RDU), a developing unified cosmological model by independent researcher Joshua Knoechelman.

footer_text: >
  Powered by Jekyll with al-folio theme. Hosted by GitHub Pages.

# Social media profiles and contact links
social:
  - icon: envelope
    link: "mailto:Sirvapors@gmail.com"
  - icon: orcid
    link: "https://orcid.org/0009-0002-1654-8161"
  - icon: zenodo
    link: "https://zenodo.org/search?q=Knoechelman%2C%20Joshua"
  # You can add other links here if you want, for example:
  # - icon: github
  #   link: "https://github.com/srvapors"

keywords: Resonant Dark Universe, Chronos Field, Timeless Physics, Cosmology, Theoretical Physics, Aumons, Dark Resonator Core
lang: en
icon: ⚛️

# URL and location of your site
url: https://srvapors.github.io # IMPORTANT: This is your live website address
baseurl: "" # IMPORTANT: Leave this blank for a main site

# -----------------------------------------------------------------------------
# Theme (Leave these as default)
# -----------------------------------------------------------------------------
repo_theme_light: default
repo_theme_dark: dark

# -----------------------------------------------------------------------------
# Jekyll Scholar (for your publications page)
# -----------------------------------------------------------------------------

scholar:
  last_name: [Knoechelman] # This will highlight your name on publications
  first_name: [Joshua, J.]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib # We will create this file next
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_link: Details

  query: "@*"
  group_by: year
  group_order: descending

# -----------------------------------------------------------------------------
# Blog (Disabled for now, as the focus is on your papers)
# -----------------------------------------------------------------------------

blog_name: RDU News & Updates
blog_description: News and updates on the Resonant Dark Universe theory.
permalink: /blog/:year/:title/

pagination:
  enabled: false # Set to false to disable the blog page for now

# -----------------------------------------------------------------------------
# Everything below this line is technical setup for the theme.
# It is best to leave it as is.
# -----------------------------------------------------------------------------

# Layout
navbar_fixed: true
footer_fixed: true
search_enabled: true
max_width: 930px

# Jekyll settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ["_pages"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - README.md
  - vendor
keep_files:
  - CNAME
  - .nojekyll

# Plug-ins
plugins:
  - jekyll-archives-v2
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-scholar
  - jekyll-sitemap

# Sitemap settings
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed

# Optional Features
enable_math: true # enables math typesetting (uses MathJax)
enable_darkmode: true # enables switching between light/dark modes
enable_progressbar: true # enables a horizontal progress bar
